import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ✅ Import the loader provider and loader component
import { LoaderProvider } from "./context/LoaderContext";
import Loader from "@/components/Common/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "United Kingdom College of Advanced Studies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ Wrap the entire app in the loading context */}
        <LoaderProvider>
          {/* ✅ Show loader if global state says 'loading' */}
          <Loader />
          {children}
        </LoaderProvider>
      </body>
    </html>
  );
}
